### ISSUE TITLE
Figures appear not to be closing?

### ISSUE THREAD

**Issue by Kazjon** [Kazjon/birdgrid#14]
When I run this I'm getting a warning:

RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).

This leads to quite a lot of memory usage, and can be avoided by making sure that everything's being closed.  It looks like a plt.close() is missing from plot_observation_frequency?

**Comment by SwarnaVallurupalli** [comment]
I have added plt.close() now. It shouldn't raise that warning now.
