### ISSUE TITLE
Crash due to second param in plot_birds_over_time

### ISSUE THREAD

**Issue by Kazjon** [Kazjon/birdgrid#15]
When I run the current version I get:

```
Traceback (most recent call last):
  File "birdgrid_timeseries.py", line 35, in <module>
    plot_birds_over_time(location,SPECIES)
TypeError: plot_birds_over_time() takes exactly 1 argument (2 given)
```

It seems like the SPECIES param isn't used by the current version.  Can you look into why that is being specified and why it works for you but not for me?

**Comment by SwarnaVallurupalli** [comment]
The current version doesn't take SPECIES param. I have corrected the issue and committed the code. It should work fine now
