### ISSUE TITLE
Indexing the regression model by months

### ISSUE THREAD

**Issue by Kazjon** [Kazjon/birdgrid#16]
The data used in the regression model should be the count of months since January of the starting year, not the month and year fused together, as this creates a nonlinearity.

**Comment by Kazjon** [comment]
It looks like the best place to do this will be init_birdgrid -- the dataframe it returns should have a single "month" column that counts up from 0 instead of both a months and years column.

**Comment by SwarnaVallurupalli** [comment]
I have added a new column in the observations which are returned by the init_birdgrid function called 'timeframe' which holds the values of months starting from '0'. I used this 'timeframe' in the linear_regression model.
