### ISSUE TITLE
Switching from RANSAC to TheilSen

### ISSUE THREAD

**Issue by Kazjon** [Kazjon/birdgrid#25]
I've had trouble making the RANSAC robust regressor work, I think it does a lot better when there's more data points and clearer inlier/outlier divisions.  So I tried out a different robust regressor algorithm -- one that's a lot easier to get working, and seems to give pretty good results!

I recommend that we remove the current RANSAC code path and replace it with TheilSen, which works exactly like normal LinearRegression and takes no extra params.  I've just been using this:

'''
regr = linear_model.TheilSenRegressor()
regr.fit(TrainData,TrainData_Target)
predicted_Species_Count=regr.predict(TestData)
'''

I think we should keep the ability to switch between TheilSen and normal Linear regression as part of the "config".  Maybe there should be a config["predictor"] that can be set to "linear" or "theilsen".

**Comment by SwarnaVallurupalli** [comment]
Sure Kaz. Could you please tell me whether can I integrate the TheilSen model in code and commit it in GitHub?

**Comment by Kazjon** [comment]
Yup!  Start committing the issues as you fix them.  I’d do it myself, but I’m afraid I’ve made so many small changes to the code in the last few days it would be a mess, and totally conflict with what you’re working on. Hopefully we can re-sych our working versions in the next few days. :)

Thanks again for all the help — i know there have been tons of issues coming in at a crazy pace the last week or two, but we’re almost there!
